modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="i_slay_mobs"
version="1.0.0"
displayName="I Slay Mobs"
credits="The greatest meme from 2015"
displayURL="https://officiallysp.sytes.net"
logoFile="logo.png"
authors="Shane Pepperell"

[[dependencies.i_slay_mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



