modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="i_slay_mobs"
version="1.0.0"
displayName="I Slay Mobs"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="shane, MCreator"

[[dependencies.i_slay_mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



