modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="i_slay_mobs"
version="1.0.1"
displayName="I Slay Mobs"
credits="The greatest meme from 2015"
displayURL="https://officiallysp.sytes.net"
authors="Shane Pepperell"
description='''
Slay Slay Slay Everyday
'''

[[dependencies.i_slay_mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.i_slay_mobs]]
    modId="just_enough_items"
    mandatory=false
    ordering="NONE"
    side="BOTH"
[[dependencies.i_slay_mobs]]
    modId="curios"
    mandatory=false
    ordering="NONE"
    side="BOTH"
[[dependencies.i_slay_mobs]]
    modId="patchouli"
    mandatory=false
    ordering="NONE"
    side="BOTH"

