modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="i_slay_mobs"
version="1.4"
displayName="I Slay Mobs"
displayURL="https://officiallysp.sytes.net"
logoFile="logo.png"
credits="The greatest meme from 2015"
authors="Shane Pepperell"
description="Slay Slay Slay Everyday"

[[dependencies.i_slay_mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




